Let configure automatically infer path to installed Dovecot and don't rely on installed libtool .la files anymore (patch by Timo Sirainen).

diff --git a/configure.in b/configure.in
--- a/configure.in
+++ b/configure.in
@@ -22,22 +22,8 @@ AC_PROG_LIBTOOL
 
 AC_ARG_WITH(dovecot,
 [AC_HELP_STRING([--with-dovecot=DIR], [Dovecot base directory [../dovecot]])],
-	dovecotdir="$withval",
-	dovecotdir=../dovecot-2.0
+	dovecotdir="$withval"
 )
-old=`pwd`
-cd $dovecotdir
-dovecotdir=`pwd`
-cd $old
-AC_SUBST(dovecotdir)
-
-if ! test -f "$dovecotdir/dovecot-config"; then
-  echo
-  echo "dovecot-config not found from $dovecotdir, use --with-dovecot=PATH"
-  echo "to give path to compiled Dovecot sources or to a directory with the"
-  echo "installed dovecot-config file."
-  AC_MSG_ERROR([dovecot-config not found])
-fi
 
 # Extensions under development
 #
@@ -92,9 +78,19 @@ AC_ARG_WITH(managesieve,
         want_managesieve=yes)
 AM_CONDITIONAL(BUILD_MANAGESIEVE, test "$want_managesieve" = "yes")
 
+if test "$dovecotdir" = ""; then
+  test "x$prefix" = xNONE && prefix=$ac_default_prefix
+  dovecotdir=$prefix/lib/dovecot
+fi
+if ! test -f "$dovecotdir/dovecot-config"; then
+  echo
+  echo "dovecot-config not found from $dovecotdir, use --with-dovecot=PATH"
+  echo "to give path to compiled Dovecot sources or to a directory with the"
+  echo "installed dovecot-config file."
+  AC_MSG_ERROR([dovecot-config not found])
+fi
 eval `cat $dovecotdir/dovecot-config`
 
-AC_SUBST(MODULE_LIBS)
 AC_SUBST(moduledir)
 AC_SUBST(dovecot_pkgincludedir)
 AC_SUBST(dovecot_pkglibexecdir)
@@ -104,6 +100,10 @@ AC_SUBST(dovecot_docdir)
 AC_SUBST(LIBDOVECOT)
 AC_SUBST(LIBDOVECOT_STORAGE)
 AC_SUBST(LIBDOVECOT_LOGIN)
+
+AC_SUBST(LIBDOVECOT_DEPS)
+AC_SUBST(LIBDOVECOT_STORAGE_DEPS)
+AC_SUBST(LIBDOVECOT_LOGIN_DEPS)
 
 AC_SUBST(LIBDOVECOT_INCLUDE)
 AC_SUBST(LIBDOVECOT_LDA_INCLUDE)
